/**
 * @file Routes handling aesthetics & FX requests.
 * @author Francesco Compagnoni
 */

// Imports
// ...

// Modules
import { Method } from "../../../../../shared/Method";
import { Route } from "../../Route";
import { Codes, send } from "../../API";

// Consts
// - TODO: Load a random sample from the database and dynamically update them using repos processed.
// - TODO: Only return a subset.
const commits = [
	"UI: Replace deprecated QLayout->setMargin with setContentsMargin",
	"libobs: Add os_is_obs_plugin function",
	"ci: Add experimental Flatpak bundle",
	"build-aux: Add Flatpak manifest",
	".gitignore: Remove duplicated .DS_Store",
	"CI: Enable service integration in GitHub Actions",
	"UI: fix unable to upload and view crash report in mac",
	"deps: Update cmake_minimum_required to 2.8.12",
	"obs-outputs: Use system-wide FTL if present",
	"UI: Add interact button to source toolbar",
	"UI: Fix color of filters icon",
	"mac-virtualcam: Make DAL plugin filename case consistent",
	"CI: Fix CEF version for both Linux & macOS",
	"obs-browser: Update to 2.11.0",
	"UI: Add support for OBS_PLUGINS*_PATH env variables",
	"UI: Add virtual camera to system tray",
	"libobs-winrt: Disable WGC border on insider SDK",
	"libobs-winrt: Fix potential race crash",
	"UI: Use FileNameWithoutSpace for screenshot output",
	"rtmp-services: Use official Twitch endpoint to fetch ingests",
	"rtmp-services: update Piczel.tv recommended",
	"obs-frontend-api: Add frontend api functions for the virtual camera",
	"UI: Support FTL URLs for custom streaming service",
	"UI: Only apply passthrough DPI scaling on Windows",
	"obs-ffmpeg: Always fully restart remote media sources",
	"ftl-stream: Fix reconnect loop on FTL ingest disconnect",
	"rtmp-services: Add Glimesh service",
	"libobs: Cleanup uses of objc_msgSend in Objective-C code",
	"UI: Fix crash when no audio backends are available",
	"linux-v4l2: Improve error and debug logging",
	"Merge pull request #83 from RainwayApp/bump-2.0.5",
	"Update .env",
	"Merge pull request #82 from RainwayApp/enum-fixup",
	"Properly parse unsigned constants",
	"Merge pull request #81 from RainwayApp/2-0-4-bump",
	"Update .env",
	"Merge pull request #80 from RainwayApp/support-empty-data",
	"Fix gulp file",
	"Better support for empty data",
	"Silence compiler warning",
	"Switch to single quote for exception messages.",
	"Fix overflow issue leading to failed opcode lookup",
	"Merge pull request #70 from RainwayApp/2-0-3-bump",
	"Bump version to v2.0.3",
	"Merge pull request #69 from RainwayApp/nicer-config-behavior",
	"Refactor config, add namespace.",
	"commandline -> command-line",
	"Make bebop.json behavior nice",
	"Merge pull request #68 from RainwayApp/readme-change",
	"Denote important EOM",
	"Introduces a POP reference onto the stack",
	"Merge pull request #67 from RainwayApp/csharp-codegen-fix",
	"Fix equality code gen",
	"Merge pull request #66 from RainwayApp/fix-bebop-tools-unix",
	"Trim the returned string of GetValue",
	"Make values init only on flags",
	"Implement suggestions made by @lynn",
	"Further tool fixes",
	"Fix .NET build-tools on Unix systems",
	"Add hint",
	"2.2.6 with some extra workarounds/hacks for companion integration",
	"Fix weird sidebar bug with the latest big sur SDK on older OSes",
	"Add extra fallback for the rare people that disabled location services",
	"Merge remote-tracking branch 'refs/remotes/origin/master'",
	"Add WiFi mention",
	"Merge pull request #1143 from henrik/patch-1",
	"Merge pull request #1145 from kawarimidoll/patch-1",
	"Update Installation.md",
	"Welcome view: Grammar",
	"Add detection for running under companion (may not be needed, still working on this)",
	"Fix the fallback streaming code",
	"Fix light / dark mode detection for automatic mode and accessibility/high contrast modes",
	"Fix some misshandled hardware detection",
	"Merge remote-tracking branch 'refs/remotes/origin/master'",
	"Fix weird sidebar issue in Xcode 12.2",
	"New icon thanks to InfernoDesign",
	"Merge pull request #1120 from cheese1/master",
	"Merge remote-tracking branch 'refs/remotes/origin/master'",
	"Merge pull request #1124 from HappyTepid/patch-1",
	"Fixed typos",
	"Update CustomVideos.md",
	"Add fallback to main screen in \"only secondary\" mode when no secondary monitor is found",
	"Merge remote-tracking branch 'refs/remotes/origin/master'",
	"Merge pull request #857 from monkeytypegeorge/master",
	"Merge pull request #855 from Magical-Penguin/quote+bug",
	"Added quotes from Discord",
	"Merge remote-tracking branch 'upstream/master'",
	"parsing new line chars for quotes aswell",
	"removed message",
	"fixed new line and tabs not parsing properly",
	"Added quotes from Discord",
	"fixed one quote",
	"Merge branch 'master' of https://github.com/Miodec/monkey-type",
	"updated error message when lb load failed, and hiding the loader bar. fixes #850",
	"Merge pull request #854 from monkeytypegeorge/master",
	"Added quote to english.json",
	"Merge pull request #1810 from leinelissen/master",
	"Upgrade c++ standard to v14 to ensure compatibility with Electron v11 on macOS",
	"Update before install on ubuntu",
	"Temporarily workaround new action restrictions",
	"Bump to v0.28.0-alpha.1",
	"Merge pull request #1795 from ianhattendorf/refactor/context-awareness",
	"Check for latest node version when running tests",
	"Require 12.19.0+ or 14.10.0+ due to async cleanup",
	"Merge pull request #1797 from ianhattendorf/fix/longpaths-enum",
	"Test clone to long path",
	"Update longpath enums to match libgit2",
	"Fix ordering issue on Windows",
	"Use a better data type for data on uv_async_t",
	"Build a cleanup handle that can be deleted by last user",
	"Don't leak jsThreadCallbackAsync",
	"Test on node 14 only until backport of required node PR",
	"Fix misc warnings",
	"Threadpool shutdown uv_close asynchronously",
	"Only test worker_threads if they are available",
	"Stick to c++11 for a little bit longer",
	"Verify context before running cppCallback",
	"Remove duplicate locks",
	"More reliable worker thread test",
	"Allow nodegit to run via worker thread or web worker",
	"Test clone via worker thread",
	"Enable module from workers",
	"Cleanup manual template batons",
	"Value initialize manual template batons as well",
	"Use freeFunctionName to free returned args on error",
	"Value initialize batons"
];

// Route
let route : Array<Route> = [{
	method: Method.GET,
	url: "/api/fx/commits",
	handler: (request: any, response: any) => {
		send(response, Codes.OK, {
			commits
		});
	}
}];

export default route;